title: D-tech
email: null@gmail.com
description: "D-tech"
baseurl: "/"
url: "https://D-techwsp.github.io"
twitter_username: best magisk module
github_username:  best magisk
author: D-tech


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
